/* eslint-disable no-useless-escape, no-dublicate-imports */
export const GET_ORDER_CALCULATIONS = 'GET_ORDER_CALCULATIONS';
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const GET_PAYPAL_TOKEN = 'GET_PAYPAL_TOKEN';
export const SYNC_USER_TO_DATASTORE = 'SYNC_USER_TO_DATASTORE';
export const SYNC_USER_LOCALLY_AND_FIREBASE = 'SYNC_USER_LOCALLY_AND_FIREBASE';
export const GET_MPESA_PUSH_API_TOKEN = 'GET_MPESA_PUSH_API_TOKEN';
export const CHECKOUT_WITH_MPESA = 'CHECKOUT_WITH_MPESA';
