export const GET_ORDER_CALCULATIONS = 'GET_ORDER_CALCULATIONS';
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const GET_PAYPAL_TOKEN = 'GET_PAYPAL_TOKEN';
export const SYNC_USER_TO_DATASTORE = 'SYNC_USER_TO_DATASTORE';
export const SYNC_USER_LOCALLY_AND_FIREBASE = 'SYNC_USER_LOCALLY_AND_FIREBASE';
